require 'rake'
require 'rspec/core/rake_task'
require 'yaml'

properties = YAML.load_file('properties.yaml')

clusterreport,nodesreport = `sudo su hdfs -c 'hdfs dfsadmin -report'`.split("\n\n-------------------------------------------------\n")
nodesreplist=nodesreport.strip.split("\n")

livenodes = nodesreplist.grep(/Live/)[0].split(" ")[2].delete("():")
nodenamelist = nodesreplist.grep(/Name/)
nodenamelist = nodenamelist.map! { |n| n.split(":")[0] == "Name" ? n.split(":")[1].strip : n }.sort
nodenamelist = ["172.16.68.3", "172.16.68.2", "172.16.68.4", "172.16.68.5", "172.16.68.6", "172.16.68.7"]

task :spec => 'spec:all'
task :default => :spec 

namespace :spec do
  task :all => nodenamelist.map {|h| 'spec:' + h}
  nodenamelist.each do |host|
    begin
      desc "Run serverspec to #{host}"
      RSpec::Core::RakeTask.new(host) do |t|
        ENV['TARGET_HOST'] = host
        t.pattern = "spec/shared/*_spec.rb"
        t.fail_on_error = false
        t.rspec_opts = "--format json --out /tmp/#{host}.json"
      end 
    rescue
	puts "Rescue entered"
    end
  end 
end
